#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xfdesktop
Version  : 4.13.2
Release  : 20
URL      : http://archive.xfce.org/src/xfce/xfdesktop/4.13/xfdesktop-4.13.2.tar.bz2
Source0  : http://archive.xfce.org/src/xfce/xfdesktop/4.13/xfdesktop-4.13.2.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: xfdesktop-bin = %{version}-%{release}
Requires: xfdesktop-data = %{version}-%{release}
Requires: xfdesktop-license = %{version}-%{release}
Requires: xfdesktop-locales = %{version}-%{release}
Requires: xfdesktop-man = %{version}-%{release}
BuildRequires : Thunar-dev
BuildRequires : intltool
BuildRequires : libnotify-dev
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(exo-1)
BuildRequires : pkgconfig(exo-2)
BuildRequires : pkgconfig(garcon-1)
BuildRequires : pkgconfig(garcon-gtk3-1)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libwnck-1.0)
BuildRequires : pkgconfig(libwnck-3.0)
BuildRequires : pkgconfig(libxfce4ui-1)
BuildRequires : pkgconfig(libxfce4ui-2)
BuildRequires : pkgconfig(libxfce4util-1.0)
BuildRequires : pkgconfig(libxfconf-0)
BuildRequires : pkgconfig(sm)
BuildRequires : sed
Patch1: 0001-Set-default-wallpaper.patch

%description
================================
WHAT IS IT?
~~~~~~~~~~~
Xfdesktop is a desktop manager for the Xfce Desktop Environment. Desktop
in this respect means the root window (or, rather, a window that sits on top
of the root window). The manager handles the following tasks:
- background image / color
- root menu, window list
- minimized app icons
- file icons on the desktop (using Thunar libs)

%package bin
Summary: bin components for the xfdesktop package.
Group: Binaries
Requires: xfdesktop-data = %{version}-%{release}
Requires: xfdesktop-license = %{version}-%{release}
Requires: xfdesktop-man = %{version}-%{release}

%description bin
bin components for the xfdesktop package.


%package data
Summary: data components for the xfdesktop package.
Group: Data

%description data
data components for the xfdesktop package.


%package license
Summary: license components for the xfdesktop package.
Group: Default

%description license
license components for the xfdesktop package.


%package locales
Summary: locales components for the xfdesktop package.
Group: Default

%description locales
locales components for the xfdesktop package.


%package man
Summary: man components for the xfdesktop package.
Group: Default

%description man
man components for the xfdesktop package.


%prep
%setup -q -n xfdesktop-4.13.2
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1542225067
export CFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
%configure --disable-static --enable-thunarx --enable-file-icons --enable-desktop-icons
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1542225067
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xfdesktop
cp COPYING %{buildroot}/usr/share/package-licenses/xfdesktop/COPYING
%make_install
%find_lang xfdesktop

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xfdesktop
/usr/bin/xfdesktop-settings

%files data
%defattr(-,root,root,-)
/usr/share/applications/xfce-backdrop-settings.desktop
/usr/share/backgrounds/xfce/xfce-blue.jpg
/usr/share/backgrounds/xfce/xfce-teal.jpg
/usr/share/icons/hicolor/32x32/apps/xfce4-backdrop.png
/usr/share/icons/hicolor/32x32/apps/xfce4-menueditor.png
/usr/share/icons/hicolor/48x48/apps/xfce4-backdrop.png
/usr/share/icons/hicolor/48x48/apps/xfce4-menueditor.png
/usr/share/icons/hicolor/scalable/apps/xfce4-backdrop.svg
/usr/share/icons/hicolor/scalable/apps/xfce4-menueditor.svg
/usr/share/pixmaps/xfce4_xicon.png
/usr/share/pixmaps/xfce4_xicon1.png
/usr/share/pixmaps/xfce4_xicon2.png
/usr/share/pixmaps/xfce4_xicon3.png
/usr/share/pixmaps/xfce4_xicon4.png
/usr/share/pixmaps/xfdesktop/xfdesktop-fallback-icon.png

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xfdesktop/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xfdesktop.1

%files locales -f xfdesktop.lang
%defattr(-,root,root,-)

