#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xfdesktop
Version  : 4.16.0
Release  : 32
URL      : https://archive.xfce.org/src/xfce/xfdesktop/4.16/xfdesktop-4.16.0.tar.bz2
Source0  : https://archive.xfce.org/src/xfce/xfdesktop/4.16/xfdesktop-4.16.0.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: xfdesktop-bin = %{version}-%{release}
Requires: xfdesktop-data = %{version}-%{release}
Requires: xfdesktop-license = %{version}-%{release}
Requires: xfdesktop-locales = %{version}-%{release}
Requires: xfdesktop-man = %{version}-%{release}
BuildRequires : Thunar-dev
BuildRequires : intltool
BuildRequires : libnotify-dev
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(exo-2)
BuildRequires : pkgconfig(garcon-1)
BuildRequires : pkgconfig(garcon-gtk3-1)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libwnck-1.0)
BuildRequires : pkgconfig(libwnck-3.0)
BuildRequires : pkgconfig(libxfce4ui-2)
BuildRequires : pkgconfig(libxfce4util-1.0)
BuildRequires : pkgconfig(libxfconf-0)
BuildRequires : pkgconfig(sm)
BuildRequires : sed
Patch1: 0001-Set-default-wallpaper.patch

%description
[![License](https://img.shields.io/badge/License-GPL%20v2-blue.svg)](https://gitlab.xfce.org/xfce/xfdesktop/-/blob/master/COPYING)

%package bin
Summary: bin components for the xfdesktop package.
Group: Binaries
Requires: xfdesktop-data = %{version}-%{release}
Requires: xfdesktop-license = %{version}-%{release}

%description bin
bin components for the xfdesktop package.


%package data
Summary: data components for the xfdesktop package.
Group: Data

%description data
data components for the xfdesktop package.


%package license
Summary: license components for the xfdesktop package.
Group: Default

%description license
license components for the xfdesktop package.


%package locales
Summary: locales components for the xfdesktop package.
Group: Default

%description locales
locales components for the xfdesktop package.


%package man
Summary: man components for the xfdesktop package.
Group: Default

%description man
man components for the xfdesktop package.


%prep
%setup -q -n xfdesktop-4.16.0
cd %{_builddir}/xfdesktop-4.16.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1609288130
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
%configure --disable-static --enable-thunarx --enable-file-icons --enable-desktop-icons
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1609288130
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xfdesktop
cp %{_builddir}/xfdesktop-4.16.0/COPYING %{buildroot}/usr/share/package-licenses/xfdesktop/dfac199a7539a404407098a2541b9482279f690d
%make_install
%find_lang xfdesktop

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xfdesktop
/usr/bin/xfdesktop-settings

%files data
%defattr(-,root,root,-)
/usr/share/applications/xfce-backdrop-settings.desktop
/usr/share/backgrounds/xfce/xfce-blue.jpg
/usr/share/backgrounds/xfce/xfce-stripes.png
/usr/share/backgrounds/xfce/xfce-teal.jpg
/usr/share/backgrounds/xfce/xfce-verticals.png
/usr/share/icons/hicolor/128x128/apps/org.xfce.xfdesktop.png
/usr/share/icons/hicolor/16x16/apps/org.xfce.xfdesktop.png
/usr/share/icons/hicolor/24x24/apps/org.xfce.xfdesktop.png
/usr/share/icons/hicolor/32x32/apps/org.xfce.xfdesktop.png
/usr/share/icons/hicolor/48x48/apps/org.xfce.xfdesktop.png
/usr/share/icons/hicolor/scalable/apps/org.xfce.xfdesktop.svg
/usr/share/pixmaps/xfce4_xicon.png
/usr/share/pixmaps/xfce4_xicon1.png
/usr/share/pixmaps/xfce4_xicon2.png
/usr/share/pixmaps/xfce4_xicon3.png
/usr/share/pixmaps/xfce4_xicon4.png
/usr/share/pixmaps/xfdesktop/xfdesktop-fallback-icon.png

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xfdesktop/dfac199a7539a404407098a2541b9482279f690d

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xfdesktop.1

%files locales -f xfdesktop.lang
%defattr(-,root,root,-)

